/*
    Jack Hershey's Stock Trader
    jhershey@primenet.com
    Author: Nick Schmitz
    Date: 9/29/99

Command Line:

    C:>JHSCN XYZ DATE DBG


Tuning Needs:
1. Number of days to hold open a DU trigger = 7 days
2. Number of days after a Sale, before retrigger on DU = 5 day
3. Buy based on Volume > 2.5 * DU vol.
4. Sell based on Volume < 1.8 * DU vol.

5. DU Vol tests:
    if (   (mav20[0]>2.1*mav5[0])
       || ((mav20[0]>2.0*mav3[5]) && (mav3[2]>mav3[0]))
       || ((mav20[0]>2.0*mav5[2]) && (mav5[2]>mav3[0])) ){

6. Buy Limits:
	xvl=high+(high-lowp)/3+0.25;
	xv2=hgcl[1]+(hgcl[1]-lwcl[1])/4+0.25;
	if (xvl>20) xvl=xvl+0.80;
	if (xv2>20) xv2=xv2+0.80;

7. Sell Stop Limits:
	xvl=tprc-(high-lowp)/2-0.50;
	xv2=lwcl[1]-(hgcl[1]-lwcl[1])/2-0.50;
	if (xvl>20) xvl=xvl-0.80;
	if (xv2>20) xv2=xv2-0.80;

Terminology:
    tprc = (high+low)/2;
    [0] - is current day
    [1] - yesterday
    mav20  - 20 day moving average of volume, calculated:
        mav20[0]=(19*mav20[0]+tvol)/20.0;
    hgcl[1], lwcl[1] - yesterday's high & low of day.

Tuning results:
0. Univ.txt & Trading range is big issue - keep constant
	~140 BN-90 is top 10% EG & RS, ~400 BN-80 top 20%
    Buy price screens $4.90, mav20>9900 used. $10k invest.

    Initial ~240 trades $680 BN-90, ~630 trade $520 BN-80
    Final   ~140 trades $750 BN-90, ~380 trade $510 BN-80

1. Loose limits on DU test & Buy ~380 Trade & 5.1% return BN-80
	2.0 * DU trigger * L*
  Tight limits on DU test & Buy ~110 Trade & 6.5% return BN-80
	2.9 * DU triger  * T*
  V.Loose limit 1.8 * DU -> 580 Trade & 4.5 % return.

3. Stop limit  has +/- 0.5% on return, spread / 2,3,4, offset 0.3-1.0
4. Sell volume has +/- 0.5% on return, 1.5, 1.8 2.1 *S*

5. Dry-up time out 9 days,
	5d-> 270 T, 4.4%, 7d-> 310 T, 5.2%, 9d-> 370 T 5.3%

6. Trading lock-outs have weak effect +/- 0.3% >-4.0 = 5 day
7. Enable jhti indicator {7,0,1 Trades} 7.3%->5.4% return.

8. Refine jhti 2 terms not one, [0]>[1] & [0]>[2]
9. Other jhti's - work, but more testing necessary.
	some hurt # trades, increase string of negative returns
10. memory of 2 jhti's in trading range in row

	jh,  15126,    483,   2979,    262223,    543,
	jh,  15545,    356,   2195,    187317,    526,
	!!    -500,    56, !!    -500,    48,
	!!      50,   138, !!      50,   103,

11. 2-day trades 22%-> 8%, use mav5, instead of tvol in sell test

12. Gotcha: Buy limit below open! - does not track tprc before buy.

*/
/*----------------------------------------------------------------*/
/* Overview:
 Program reads TC2k data from Explicit location (f:\tc2000cd\x\xyz.ndx)
 or from name generated by adding to XYZ argument passed on Command line
    C:\tc2000\data\x\XYZ.ndx

 Second argument is date (960907) for beginning of analysis period.

 Suggestion: use 1 year for Osc finding, <90 day for Ramp detection.

 Third & fourth argument is debug level (presence detection).

 Trades are initiated using 0..7 cycle - P/V/AD code.

 Buy is at low point, sell is at high. Must be $1.50 apart & $100
 commission charged. $10k investment used for share calculations.

*/
/*----------------------------------------------------------------*/
#include <stdio.h>
#include <math.h>
#include <alloc.h>/**/

#define MAX_LINE_LENGTH  120
char a_str[256], b_str[256], c_str[256], sLoc[256];
char x_str[256], y_str[256], z_str[256], time[256], chx;

FILE	*fp,		/* Binary - tc2k file */
	*fx,		/* list of stocks */
	*fh,		/* html output */
	*fa, *fb;	/* result of scan - action, stocks */

int dbg, lop, lnc, ln, fa_ctr, flx, mxf, csv;	/* control vars */
float high, lowp, clse, opnp, tvol;		/* tc2k data /**/
float tprc, lcse, date, lstp, lstc, lstv, ldat, zdat;

/*----------------------------------------------------------------*/
float mav3[9], mav5[9], mav20[9], map3[9], map5[9], map20[9];
float msv3[9], msv5[9], msv20[9], msp3[9], msp5[9], msp20[9];
float hgcl[9], lwcl[9], rsiv[9], stcl, stch, obvi;
float pjh[3],  vjh[3],  acdn[3], tvl[31], prc[31];
float jfrs, jfpc, jfnc;

int   stck, stcd, rsio, rsia; /* Stocastic & RSI calc */
int   styk, styd, rsyo, rsya, rsby;
int   olgc; /* up/dn leg count /**/

float bb40, vb40; /* Bolinger band calc */

/*----------------------------------------------------------------*/
float ftmp, ftm2, dflg, oflg, /* direction flg */
    gmin, gmax,  /* Global max & min /**/
    rmin, rmax,  /* Relative max & min - max/min date /**/
    mndt, mxdt,
/*----------------------------------------------------------------*/
    shar, bprc,  /* Shares, buy price, buy date /**/
    bdat, mdat,  /* Buy date, min/max date /**/
    mxtr, ttrd,	 /* Max trade, this trade profit /**/
/*----------------------------------------------------------------*/
    opct, opcy,  /* Osc price today/yesterday /**/
    ovlt, ovly,  /* Osc volume today/testerday /**/
    oadt,	 /* Osc Trade acc/dist /**/
    jhti, jhto,	 /* Osc Trade cycle indicator /**/
/*----------------------------------------------------------------*/
    obal, odat,  /* Osc Trading balance & trading days /**/
    otdy, otpc,  /* Osc info  temp day & price/**/
    olrg,
    oshr, otmp,  /* Osc - shares & profit /**/
    ostl, otrd,  /* Stop Limit,  # trades */
    oshr, 	 /* # shares bought */
    oduv, odud,  /* Dry Up volume, DU date time out */
    ohst, ojhi,
    osld,	 /* last sale price */
/*----------------------------------------------------------------*/
    tbal, tday,	 /* Trading balance & trading days /**/
    ttrd, tstk,  /* #trade */
    tlrg, tsml,  /* Largest & smallest obal */
    acdt;	 /* Acc/Dist temp var */

int phst[7], dhst[7], pbin[7], dbin[7];
/*----------------------------------------------------------------*/
/* Main output display /**/
/*----------------------------------------------------------------*/
void out_dsp()  {
float xv3, xv4, xv5;
    if (rmin>0.0) xv3=rmax/rmin; else xv3=99.9;
    if (otrd>0.0) xv3=obal/otrd/1000.0; else xv3=0.1;
	xv4=100*(tprc-rmin)/(rmax-rmin);
	if (otpc>0) xv5=100*tprc/otpc-100; else xv5=0;

/*-----------------------------------------------------*/
	if (odat>0) tstk++;
	tday=tday+odat;
	ttrd=ttrd+otrd;
	tbal=tbal+obal;
	if (obal>tlrg) tlrg=obal;
	if ((obal<tsml) && (otrd>0)) tsml=obal;
/*-----------------------------------------------------*/
   if ((fa!=NULL) && (lop>1) && (osld>0.0) && (tprc>0.0)) {
    if (fb!=NULL) fprintf (fb,"%s+*\n",c_str); /* for html only */
/*LSCC,991119, 940.000, 46.000,41.875,991202,48.690,  2429, 269.84,  6.9 */

	fprintf (fa,";%6s,%6.0f,%8.3f,%7.3f,%6.3f,%6.0f,%6.3f,%6.0f\n",
		c_str,   date, oshr,  osld, clse,   date, clse, otmp);

    fprintf (fa,"!$ sell, %6.1f, %6s, %6.0f,  %6.2f, %6.0f, %6.2f, %6.0f,",
                xv3,    c_str,   date,   clse,  oshr,  osld,  obal );
    fprintf(fa," $%c, %2.0f, %5.0f\n",
		chx, ojhi, otmp);/**/
    	}
/*-----------------------------------------------------*/
    if ((otdy<0.0) && (odud>0.0)) { /* not yet bought */

    if (lop>1) {
	if ((fb!=NULL) && (tprc>0.0))
    		fprintf (fb,"%s+\n",c_str); /* for html only */

        if ((fa!=NULL)
	  && (tprc>2.5) && (mav20[0]>9900.0) /* liguid non-dog */
	  && (rmax<79) ){ /* arbitrary choice */
/*	  && (rmax>1.2*rmin) && (rmax<79) ){ /* arbitrary choice */
    		fa_ctr++;
fprintf (fa,"!$ .wtc, %6.1f, %6s, %6.0f,  %6.2f, %6.0f, %6.2f,%7.0f,%4.0f,%4.0f\n",
		tvol/oduv, c_str, date,   ostl, oshr, tprc,   oduv, jhti, odud);}/**/
      }

    printf ("\n!$  wtc, %6.1f, %6s, %6.0f,  %6.2f, %6.0f, %6.2f,%7.0f,%4.0f,%4.0f\n",
		tvol/oduv, c_str, date,   ostl, oshr, tprc,   oduv, jhti, odud);/**/
/*  printf ("\n!$  wtc, %6.1f, %6s, %6.0f,  %6.2f, %6.0f, %6.2f,  %8.0f\n",
            xv3, c_str, date,   ostl, oshr, tprc,   oduv);/**/
    }
/*-----------------------------------------------------*/
   if ((odud>0.0) && (otdy>0.0)) { /* stock owned */
    if (lop>1) {
	if ((fb!=NULL) && (tprc>0.0))
    		fprintf (fb,"%s+*\n",c_str); /* for html only */
/*LSCC,991119, 940.000, 46.000,41.875,991202,48.690,  2429, 269.84,  6.9 */
      }

   if ((fa!=NULL) && (lop>1) && (tprc>0.0)) {
    if (otdy==1) {
	fprintf (fa,";%6s,%6.0f,%8.3f,%7.3f,%6.3f,%6.0f,%6.3f\n",
		c_str,   date, oshr,  otpc, ostl,   date, otpc);

      fprintf (fa,"!$ ~buy, %6.1f, %6s, %6.0f,  %6.2f, %6.0f, %6.2f,  %5.2f, %5.2f, %6.0f\n",
        xv3, c_str, date,   ostl, oshr, otpc,     rmin, rmax, oduv);}/**/
    if (otdy!=1) {
	fprintf (fa,"!$ slmt, %6.1f, %6s, %6.0f,  %6.2f, %6.0f, %6.2f,",
			tvol/oduv, c_str, date,   ostl, oshr, otpc);
	fprintf (fa,"  %5.0f, %5.1f,%3.0f,%3.0f\n",
			xv4, xv3, xv5, otdy);}/**/
    }

   printf ("\n!$  buy, %6.1f, %6s, %6.0f,  %6.2f, %6.0f,%6.2f, %5.2f, %5.2f, %2.0f\n",
            xv3, c_str, date,   ostl, oshr, tprc,     rmin, rmax, otdy);/**/
  }

/*-----------------------------------------------------*/
   if (otrd>0) /* summary of all trades */
    printf ("\n$!$  jh, %6s, %6.0f, %6.0f,%8.0f, %6.0f,%6.0f,%6.1f,%6.1f, %5.0f\n",
		c_str, otrd, odat,  obal, obal/otrd, obal/odat, odat/otrd, rmin, tvol);/**/
    else printf ("\n$.$  jh, %6s\n", c_str);
} /* out_dsp */

/*----------------------------------------------------------------*/
void wrt_key()  {
if (dbg>1) {
    printf ("\nDebug Key:\n");
    printf ("...............................................................................\n");
    printf ("Date, JHI, vt1, vt2, vt3,txyz,.,   vlA,  vlB,DUd,  High,  $Prc,   Low, StLmt,Cd\n");
    printf ("981117, 4, 0.3, 3.0, 0.3,    ,.,  1128, 28.9, 10, 16.88, 15.38, 13.88, 13.18,+.\n");
    printf ("\n$.$  jh,   StkN,   #Trd,#DayOwn, Balance$, $/Trd, $/Day, Day/Trd\n");
    printf ("$.$  jh,   gmai,      8,     27,    19005,  1234,   703,   3.4\n");

    printf ("\nActions:\n");
    printf ("...............................................................................\n");
    printf ("ActnCde, rMx/Mn,   StkN,   Date,  StpLmt,  #Shrs, $tPrc, {Misc}\n");
    printf ("$! bwtc,   1.67,   gmai, 981112,   10.55,   1000, 10.32,     29544\n");
    printf ("$!  Buy,   5.03,   gmai, 981112,    5.32,   1800,  8.17,  1.63,  8.17,#.\n");
    printf ("$!  Lmt,   5.03,   gmai, 981112,    5.32,   1800,  8.17,  1.63,  8.17,#.\n");
    printf ("$! Sell,  10.30,   gmai, 981118,    5.32,   1800, 13.18,14159,$.7, 5, 14159\n");
    printf ("\nWtc  - Watch - Misc = {DU Vol}\n");
    printf ("Buy  - Misc = {Rmin, Rmax, #Days}\n");
    printf ("SLmt - Stop Limit Change - Misc = {Rmin, Rmax, #Days}\n");
    printf ("Sell - Misc = {Balance, Code, JHI, #Days, Profit}\n");
    printf ("...............................................................................\n");
}
} /* wrt_key */

/*----------------------------------------------------------------*/
void dsp_hst()  {
int q,r,s;
	printf("\nProfit Histogram:\n");
	printf("!!\n");
	for (q=0; (q<6); q++ ) printf("!! <= $ %6d,%6d,\n",pbin[q],phst[q]);
	printf("!!    >   $ 5k,%6d,\n",phst[6]);
	printf("\nDay Histogram:\n");
	printf("!!\n");
	for (q=0; (q<6); q++ ) printf("!! <=   %6d,%6d,\n",dbin[q],dhst[q]);
	printf("!!    >    16d,%6d,\n",dhst[6]);
	printf("\n");

/*	s=r=0;	for (q=0; (q<7); q++ ) { r=r+dhst[q]; s=s+dhst[q]; }
	printf("\n%d %6.0f\n",r,s);/**/
}/* dsp_hst */

/*----------------------------------------------------------------*/
void do_hst(int day, int prft)  {
int q,r,s;
	r=-1;
	for (q=0; ((q<7) && (r<0)); q++ ) if (prft<=pbin[q]) r=q;
	if (r>=0) phst[r]++; else phst[6]++;

	s=-1;
	for (q=0; ((q<7) && (s<0)); q++ ) if (day<=dbin[q]) s=q;
	if (s>=0) dhst[s]++; else dhst[6]++;

/*	printf("$!!$ %3d, %3d, %3d %3d\n", day,s, prft,r); /**/
} /* do_hst */

/*----------------------------------------------------------------*/
void ck_trade() { int x; /* temp for shar calc */
float xvl, xv2, xv3, xv4, xv5;
char ch1, ch2,ch3,ch4;

	if (rmin>0.0) xv3=rmax/rmin; else xv3=99.9;
	if (otrd>0.0) xv3=obal/otrd/1000.0; else xv3=0.1;
	xv4=100*(tprc-rmin)/(rmax-rmin);
	if (otpc>0) xv5=100*tprc/otpc-100; else xv5=0;
/*----------------------------------------------------------------*/
/*jhershey@primenet.com - indicator */

	opcy=opct;      ovly=ovlt;	jhto=jhti;
	if (map5[0]>=map20[0]) opct=1.0; else opct=0.0; /* price rise */
    if (mav5[0]>=mav20[0]) ovlt=1.0; else ovlt=0.0; /* vol rise */

	if (map5[0]>map5[1]) opct=1.0; else opct=0.0; /* price rise */
    if (mav5[0]>mav5[1]) ovlt=1.0; else ovlt=0.0; /* vol rise */

	if (pjh[0]>pjh[1])	opct=1.0; else opct=0.0; /* price rise */
	if (vjh[0]>vjh[1])	ovlt=1.0; else ovlt=0.0; /* vol rise */
	if ((acdn[0]>acdn[1]) && (acdn[0]>acdn[2])) oadt=1.0; else oadt=0.0;
/* jf's */
/* if(pjh[0]>0)
	if (fabs(pjh[0]-pjh[1])/pjh[0]>0.05)	opct=1.0; else opct=0.0;
	if (fabs(pjh[0]-pjh[1])>0.25)	opct=1.0; else opct=0.0;
	if (vjh[0]>vjh[1])		ovlt=1.0; else ovlt=0.0;
	if ((jfrs>55.0) || (jfrs<45.0))	oadt=1.0; else oadt=0.0; /* acc/dist */
/* best */
	if ((pjh[0]>pjh[1]) && (pjh[0]>pjh[2])) opct=1.0; else opct=0.0;
	if ((vjh[0]>vjh[1]) && (vjh[0]>vjh[2])) ovlt=1.0; else ovlt=0.0;
	if (acdn[0]>acdn[1])	oadt=1.0; else oadt=0.0; /* acc/dist */
	jhti=4*opct+2*ovlt+oadt; /* combine as weighted digit */

/*----------------------------------------------------------------*/
if (dbg>2) {
	printf("*.*,%6.0f, %4.0f,%4.0f, %4.0f,%4.0f,",
         date  , tvol/100, mav20[0]/100, mav5[0]/100, mav3[0]/100);
	printf("%4.0f, %4.0f,%4.0f\n",
         	msv20[0]/100, msv5[0]/100, msv3[0]/100);}
if (dbg>2) {
	printf("***,%6.0f,%3.0f,%3.0f,%3.0f,  %3.0f,%6.3f, %6.0f,,",
         date  , -4*opct, -2*ovlt, -1*oadt, -1*jhti, tprc, tvol/20000);

	printf("%6.3f,%6.0f,%6.3f,,",
         tprc,   10*opct, 5*pjh[0]);
	printf("%5.0f,%5.0f,%5.0f,,",
	  5000*ovlt, vjh[0]/10.0, tvol/100.0);
	printf("%5.0f,%6.0f, %6.2f, %6.0f,,",
	  jfrs,30*oadt, tprc, tvol/20000.0 );
	printf("%5.0f,%5.0f,%6.3f,%5.0f,%5.0f\n",
      tvol/10000, 10*oadt, tprc, acdn[0]/1000, acdt/1000);} /**/
/*----------------------------------------------------------------*/
/* time outs  */

	if ((otdy<0.0) && (odud>6.0)) {odud=-7.0; ostl=-1.0;}
	if (odud>0.0) odud++;
	if (otdy>0.0) otdy++;
	if (otdy<-2.1) otdy++;
	if (odud<-2.1) odud++;
	if (osld>0.0) osld=-1.0;

/*----------------------------------------------------------------*/
/*Sell test */

	if (  (odud>0.0) && (otdy>0.0) /* owned */
/*	   && ( (tvol<1.8*oduv)	|| (lowp<ostl) ) ){ /**/
       && ( (mav5[0]<2.0*oduv) || (lowp<ostl) || (otdy>16.0)) ){ /*S*/

		chx='v';
		if (lowp>ostl) ostl=tprc; /* volume limit */
			else chx='p';
		if (otdy>16.0) { chx='t'; ostl=tprc;} /* time limit */

	    	otmp=oshr*(ostl-otpc);	
        	osld=ostl;
    	
    		if (otmp>olrg) olrg=otmp; /* save biggest */
    		if (otmp>800)  olgc++;
    		if (otmp>1900) olgc++;

        	odat=odat+otdy;
        	obal=obal+otmp;

		do_hst(otdy,otmp);/**/

/*----------------------------------------------------------------*/
if (dbg>0) {
    printf ("$! sell, %6.2f, %6s, %6.0f,  %6.2f, %6.0f,%6.2f,%6.0f,",
		xv3, c_str, date,   otpc,  oshr,  osld, obal);

	printf("$%c%1.0f,%2.0f, %5.0f\n",
		chx, ojhi, otdy, otmp);}/**/

		odud=-7.0;	otdy=-7.0;	ostl=-1.0;
    	}

/*----------------------------------------------------------------*/
/*Buy test */

	if ( (odud>0.0) && (otdy<0.0) /* DU Triggered */
	  && (tvol>2.5*oduv) && (high>ostl) /* L*/

/*	&& ((opnp/ostl)<1.05) /* gap up */
/*	  && (tvol>3.5*oduv) && (high>ostl) /* T*/
/*	  && (tvol>3.0*oduv) && (high>ostl) /* L*/
/*	&& (opnp<ostl) /* no gap */
/*	&& (lowp<ostl) /* Timing! */

	&& ((jhto>6.1) || (jhto<1.1) || (jhti>6.1) || (jhti<1.1)) /*7,0,1*/
	  && (tprc>2.5) && (mav20[0]>9900.0) /* liguid non-dog */
	  && (rmax<79) ){ /* arbitrary choice */
/*	  && (rmax>1.2*rmin) && (rmax<79) ){ /* arbitrary choice */

	printf ("\n$! bwtc, %6.2f, %6s, %6.0f,  %6.2f, %6.0f,%6.2f,%6.0f, %8.0f",
        	xv3, c_str,     date,  ostl, oshr, tprc, odud, oduv);/**/

		otpc=ostl;
		if (lowp>ostl) otpc=lowp; /* gap-up */
		if (opnp>ostl) otpc=opnp; /* gap-up */

		x=1000/otpc;	/* shares rounded to x00 */
		oshr=10.0*x;
		otdy=1.0;
		otrd++;

		chx='1';
		if (mav20[0]>2.0*mav3[5]) chx='2';
		if (mav20[0]>2.0*mav5[2]) chx='3';
		ojhi=jhti; /* save on buy */

/*----------------------------------------------------------------*/
if (dbg>0) {
      printf ("\n$!  buy, %6.2f, %6s, %6.0f,  %6.2f, %6.0f,%6.2f,",
			xv3, c_str, date,   otpc, oshr, tprc);

      printf (" %5.2f, %5.2f,#%c\n",
		rmin, rmax, chx);/**/
    	}}

/*----------------------------------------------------------------*/
/*Dry Up Vol trigger */
    ch1=ch2=ch3=ch4=' ';

    if ( (otdy<0.0) && (otdy>-4.0) && (odud>-4.0)
	&& ((jhto>6.1) || (jhto<1.1) || (jhti>6.1) || (jhti<1.1)) /*7,0,1*/)

/*--------------------------------------------------------*/
/*       if ( (mav20[0]>2.1*mav5[0])
	|| ((mav20[0]>2.0*mav3[5]) && (mav3[2]>mav3[0]))
	|| ((mav20[0]>2.0*mav5[2]) && (mav5[2]>mav3[0])) ) {/* L*/

/*--------------------------------------------------------*/
      if (( (msv20[0]>2.7*msv5[0])
	|| ((msv20[0]>2.5*msv3[5]) && (msv3[2]>msv3[0]))
	|| ((msv20[0]>2.5*msv5[2]) && (msv5[2]>msv3[0])) )

	|| ( (mav20[0]>2.1*mav5[0])
	|| ((mav20[0]>2.0*mav3[5]) && (mav3[2]>mav3[0]))
	|| ((mav20[0]>2.0*mav5[2]) && (mav5[2]>mav3[0])) )) {/* */
/*--------------------------------------------------------*/

/*	|| (mav20[0]>3.9*tvol) /* removed 10/6 */
/*	|| ((mav20[0]>3.9*tvol) && (mav5[2]>mav3[0])) /**/
/*	|| ((tvol>4.5*lstv) && (mav20[0]>mav3[2]))/**/
/*	|| (mav20[0]>2.0*mav3[5]) || (mav20[0]>2.0*mav5[2])) { /**/

	if (odud>5.0) odud=1.0;
	if (odud<0.0) { odud=1.0; ostl=-1.0; oduv=tvol;}

/*----------------------------------------------------*/
	if (tvol<oduv) oduv=tvol;	/* only lower */
        if (mav5[0]<oduv) oduv=mav5[0];
        if (mav3[0]<oduv) oduv=mav3[0];
        if (mav3[5]<oduv) oduv=mav3[5];
        if (mav5[2]<oduv) oduv=mav5[2];/**/

        if (msv5[0]<oduv) oduv=msv5[0];
        if (msv3[0]<oduv) oduv=msv3[0];
        if (msv3[5]<oduv) oduv=msv3[5];
        if (msv5[2]<oduv) oduv=msv5[2];/**/
/*----------------------------------------------------*/
   }
	if (mav20[0]>2.1*mav5[0]) ch1='t'; /* trigger display */
	if (mav20[0]>3.9*tvol)	  ch2='x';
	if (tvol>4.5*lstv) ch2='x';
	if (mav20[0]>2.0*mav3[5]) ch3='y';
	if (mav20[0]>2.0*mav5[2]) ch4='z';

	if (msv20[0]>2.7*msv5[0]) ch1='q'; /* trigger display */
	if (msv20[0]>2.5*msv3[5]) ch3='w';
	if (mav20[0]>2.5*mav5[2]) ch4='r';

/*----------------------------------------------------------------*/
/*Limits  - Buy */

	xvl=high+(high-lowp)/4+0.25;
	xv2=hgcl[1]+(hgcl[1]-lwcl[1])/4+0.25;

	if (xvl>20) xvl=xvl+0.50;
	if (xv2>20) xv2=xv2+0.50;

	if ((odud>0.0) && (otdy<0.0)) { /* not yet bought */

		chx='a';
		if (ostl<0)	{ ostl=xv2; chx='l'; } /* before DU */
		if (ostl>0)	{ ostl=xvl; chx='m'; } /* lower it */

		if ((xvl<ostl)
		   && (odud>1)) { ostl=xvl; chx='n'; } /* lower it */
		if ((xv2<ostl)
		   && (odud>1)) { ostl=xv2; chx='o'; } /* lower it */

		xvl=high+0.25;	/* Just above */
		if ((xvl<ostl)
		   && (odud>2)) { ostl=xvl; chx='p'; } /* lower it */

		x=1000/tprc;	/* shares rounded to x00 */
		oshr=10.0*x;
	  }

/*Limits  - Sell */

	xvl=tprc-(high-lowp)/4-0.35;
	xv2=lwcl[1]-(hgcl[1]-lwcl[1])/4-0.35;
	if (xvl>20) xvl=xvl-0.75;
	if (xv2>20) xv2=xv2-0.75;

	if (otdy>0.0) { /* stock owned */

		chx='b';
		if (xv2>ostl)  { ostl=xv2; chx='d'; } /* raise it */
		if (xvl>ostl)  { ostl=xvl; chx='e'; } /* raise it */
		if (otdy<2.0) {
			ostl=lowp-0.50; chx='c'; /* Just under */
			if (ostl>20) ostl=ostl-0.80;}
/*		if (ostl>lowp) { ostl=lowp-0.25; chx='e';} /* Just under */
		}
/*----------------------------------------------------------------*/
if ( (dbg>0) && (otdy>0.0) ){
	printf ("$! slmt, %6.1f, %6s, %6.0f,  %6.2f, %6.0f,%6.2f, ",
			tvol/oduv, c_str, date,   ostl, oshr, tprc);
	printf ("%5.0f, %5.1f,%3.0f,%3.0f,#%c\n",
		xv4, xv3, xv5, otdy, chx);}/**/
/*      printf ("$! slmt, %6.2f, %6s, %6.0f,  %6.2f, %6.0f,%6.2f,",
			xv3, c_str, date,   ostl, oshr, tprc);
      printf (" %5.2f, %5.2f,#%c\n",
		rmin, rmax, chx);}/**/
/*----------------------------------------------------------------*/
	if (oduv>0.0) { xvl=tvol/oduv;} else {	xvl=mav20[0]/tvol;}
	xv2=tvol/1000.0;

if (dbg>1) {
    printf ("%6.0f,%2.0f, %3.1f, %3.1f, %3.1f,%c%c%c%c",
       date, jhti, mav20[0]/mav5[0], mav20[0]/mav3[5],
        mav20[0]/mav5[2],ch1,ch2,ch3,ch4);
    printf (",!,%6.0f,%5.1f, %2.0f, %5.2f, %5.2f, %5.2f, %5.2f,+%c\n",
	   	xv2, xvl,       odud,   high, tprc, lowp,   ostl, chx );} /**/

if ((otpc>0.0) && (otdy<0.0)) {
	otpc=-1.0;
	if (dbg>1) printf ("\n");
    } chx='.';
}/* ck_trd */

/*----------------------------------------------------------------*/
void upd_ma()   { /* update maving average */
	int q;

    if (map5[0]<0.0)  { acdn[0]=acdn[1]=acdn[2]=0.001;}
      else {
 	acdn[2]=acdn[1]; acdn[1]=acdn[0];
	if (high>lowp) acdt=tvol/100*((clse-lowp)
		- (high-clse))/(high-lowp)+acdt;
	acdn[0]= (2.0*acdn[0] + acdt)/3.0;} /* 3.0 */

/*----------------------------------------------------------*/
    for (q=8; q>0; q--){
        map3[q]= map3[q-1];    mav3[q]= mav3[q-1];
        map5[q]= map5[q-1];    mav5[q]= mav5[q-1];
        map20[q]=map20[q-1];  mav20[q]=mav20[q-1];}
    for (q=8; q>0; q--){
        msp3[q]= msp3[q-1];    msv3[q]= msv3[q-1];
        msp5[q]= msp5[q-1];    msv5[q]= msv5[q-1];
        msp20[q]=msp20[q-1];  msv20[q]=msv20[q-1];}

/*----------------------------------------------------------*/
    if (map5[0]<0.0) {for (
		q=0; q<8; q++){
            map3[q]=tprc;   map5[q]=tprc;   map20[q]=tprc;
            mav3[q]=tvol;   mav5[q]=tvol;   mav20[q]=tvol;}
		bb40=tprc/45.0;	vb40=tvol/3.0;
		pjh[2]=pjh[1]=pjh[0]=0;
		vjh[2]=vjh[1]=vjh[0]=0;

      } else {
        map3[0] =( 2.0*map3[0] +tprc)/ 3.0; /*3*/
        map5[0] =( 4.0*map5[0] +tprc)/ 5.0; /*5*/
        map20[0]=(19.0*map20[0]+tprc)/20.0; /*20*/

        mav3[0] =( 2.0*mav3[0] +tvol)/ 3.0; /* 3 */
        mav5[0] =( 6.3*mav5[0] +tvol)/ 7.3; /* 7.5 */
        mav20[0]=(16.0*mav20[0]+tvol)/17.0; /* 17 */

/*----------------------------------------------------------*/
	for (q=29; q>0; q--){tvl[q]=tvl[q-1];  prc[q]=prc[q-1];}
	tvl[0]=tvol;	prc[0]=tprc;

	msp3[ 0]=0.01;	msp5[ 0]=0.01;	msp20[0]=0.01;
	for (q=0; q< 3; q++) msp3[ 0]=msp3[ 0]+prc[q]; msp3[ 0]=msp3[ 0]/ 3;
	for (q=0; q< 5; q++) msp5[ 0]=msp5[ 0]+prc[q]; msp5[ 0]=msp5[ 0]/ 5;
	for (q=0; q<30; q++) msp20[0]=msp20[0]+prc[q]; msp20[0]=msp20[0]/30;

	msv3[ 0]=1.0;	msv5[ 0]=1.0;	msv20[0]=1.0;
	for (q=0; q< 3; q++) msv3[ 0]=msv3[ 0]+tvl[q]; msv3[ 0]=msv3[ 0]/ 3;
	for (q=0; q< 5; q++) msv5[ 0]=msv5[ 0]+tvl[q]; msv5[ 0]=msv5[ 0]/ 5;
	for (q=0; q<25; q++) msv20[0]=msv20[0]+tvl[q]; msv20[0]=msv20[0]/25;
/**/
/*----------------------------------------------------------*/
        bb40=(fabs(tprc-map5[0])+39.0*bb40)/40.0;
        vb40=(fabs(tvol-mav5[0])+39.0*vb40)/40.0;

	pjh[2]=pjh[1];	pjh[1]=pjh[0];
	vjh[2]=vjh[1];	vjh[1]=vjh[0];
	pjh[0]=(4.0*pjh[0] + (map5[0]-map3[0]))/5.0;
        vjh[0]=(4.0*vjh[0] + (mav5[0]-mav3[0]))/5.0; /*nas*/

/*	pjh[0]=(map3[0]-map20[0]);
        vjh[0]=(mav5[0]-mav20[0]);
	pjh[1]=(1.5*pjh[1] + pjh[0])/2.5;
	vjh[1]=(1.5*vjh[1] + vjh[0])/2.5; /*jf*/
	if (clse>lstc) obvi=obvi+tvol/1000; else obvi=obvi-tvol/1000;
		}

/*  if (map3[0]<0.0) { map3[0] =tprc;} else { map3[0] =( 2*map3[0] +tprc)/ 3.0;}/**/

    oflg=dflg;
    if (map5[0]>map20[0]) { dflg=1.0; } else { dflg=-1.0; }

    if (oflg!=dflg) {if (dflg>0.0) rmax=0.001; else rmin=999.0;}
	if ((dflg>0.0) && (tprc>rmax)) { rmax=tprc; mdat=ln; mxdt=ln; }
	if ((dflg<0.0) && (tprc<rmin)) { rmin=tprc; mdat=ln; mndt=ln; }

    if (tprc>gmax) { gmax=tprc; }
	if (tprc<gmin) { gmin=tprc; }

/*----------------------------------------------------------------*/
/*printf("%6.0f,%6.3f,  %6.3f,%6.3f,  %6.3f,%6.0f\n",
         date  , opnp,   high,lowp,   clse, tvol);
 printf("$br$,%6.0f,%6.2f, %6d, %6d, %6d, %6d,%4d,   %6.2f, %6.0f, %6.2f %6.0f\n",
        date, tprc, stcd, rsia, stck, rsio, lnc, map5[0], mav5[0], map20[0], mav20[0]);/**/

/* printf("$br$,%6.2f,  %6.2f,%6.2f, %6.2f, %6.2f, %6.2f, %6.0f \n",
    rmin, rmax, gmin, gmax, acdt, acdn[0], dflg); /**/
} /* upd_ma */

/*----------------------------------------------------------------*/
void upd_rs()   { /* update rsi & stoc indicators */
    int q;
    for (q=8; q>0; q--) hgcl[q]=hgcl[q-1]; hgcl[0]=high;
    for (q=8; q>0; q--) lwcl[q]=lwcl[q-1]; lwcl[0]=lowp;
    for (q=8; q>0; q--) rsiv[q]=rsiv[q-1]; rsiv[0]=clse-opnp+0.001;

	styk=stck; styd=stcd; rsyo=rsio; rsya=rsia;
	stch=0.001; stcl=9999.9;
        for (q=0; q<9; q++) {
			if (stch<hgcl[q]) stch=hgcl[q];
			if (stcl>lwcl[q]) stcl=lwcl[q];
			}
/*		if (lnc>3) {stck=100*(clse-stcl) / (stch-stcl); /**/
		if (lnc>3) {stck= (3*stck + 100*(clse-stcl) / (stch-stcl+0.001))/4; /**/
			if (stcd<0) stcd=stck; else stcd=(7*stcd+stck)/8;}

/* printf("$.$,%6.2f, %6.2f, %6.2f\n",tprc,stch, stcl);/**/

/*----------------------------------------------------------------*/
/* jhfowler@fas.harvard.edu */
	if (jfrs<0) {jfrs=50.001;	jfpc=0.001;	jfnc=0.001;}
	    else {
		jfrs=100.0-100.0/(1+jfpc/jfnc);
		if (clse>=lstc) {
			jfpc=(1.5*jfpc + tvol*fabs(clse-lstc))/2.5;
		   } else {
			jfnc=(1.5*jfpc + tvol*fabs(clse-lstc))/2.5+0.001;
		   }
	  }
/*----------------------------------------------------------------*/
                stch=0.001; stcl=0.001;
        for (q=0; q<9; q++) {
			if (rsiv[q]>0.0) stch=(7*stch+rsiv[q])/8;	
			   else stcl=(7*stcl+fabs(rsiv[q]))/8; /**/
			}

/*		if (lnc>3) { rsio=100-(100/(1+(stch/stcl))); /**/
		if (lnc>3) { rsio=(3*rsio + 100-(100/(1+(stch/stcl))))/4; /**/
			if (rsia<0) rsia=rsio; else rsia=(7*rsia+rsio)/8;}
	
/* printf("$.$,%6.2f, %6.2f, %6.2f\n",tprc,stch, stcl);/**/

/*----------------------------------------------------------------*/
/* for (q=0; q<9; q++ ) printf (" %6.2f",hgcl[q]); printf("\n"); /**/
/* for (q=0; q<9; q++ ) printf (" %6.2f",lwcl[q]); printf("\n"); /**/
/* for (q=0; q<9; q++ ) printf (" %6.2f",rsiv[q]); printf("\n"); /**/

/*printf("$br$,%6.0f,%6.2f, %6.2f, %6d, %6.2f, %6d,%4d,   %6.2f, %6.0f, %6.2f %6.0f !\n",
    date, tprc, stch, rsia, stcl, rsio, lnc,       map5[0], mav5[0], map20[0], mav20[0]);/**/

if (dbg>4) {
	if (lnc>3) if ((stck>stcd) && (styk<styd))
	printf("$bs$,%6.0f,%6.2f, %6d, %6d, %6d, %6d\n",
		date, tprc, stcd, rsia, stck, rsio);
	if (lnc>3) if ((rsio>rsia) && (rsyo<rsya))
	printf("$br$,%6.0f,%6.2f, %6d, %6d, %6d, %6d\n",
		date, tprc, stcd, rsia, stck, rsio);
	} /*dbg */
} /* upd_rs */

/*----------------------------------------------------------------*/
void do_init()  {
    map3[0]=-1.0;      map5[0]=-1.0;    map20[0]=-1.0;
    mav3[0]=-1.0;      mav5[0]=-1.0;    mav20[0]=-1.0;
    bb40=-1.0;      vb40=-1.0;    dflg=1.0;

    stck=-1;	    stcd=-1;	    rsio=-1;	    rsia=-1;
    styk=-1;	    styd=-1;	    rsyo=-1;	    rsya=-1;
    gmin=999.9;     gmax=0.001;     rmin=999.9;     rmax=0.001;

    opct=-1.0;	    opcy=-1.0;	    ovlt=-1.0;	    ovly=-1.0;
    odat=0.001;     obal=0.001;     otdy=-7.0;      otpc=-1.0;
    oadt=0.01;	    olgc=0;	    odud=-7.0;	    oduv=-1.0;
    otrd=0.0;       ostl=-1.0;      ldat=0.0;	
    osld=0.0;	    tvol=-1.0;	    obvi=0.0;
    jfrs=-1.0;	    jfpc=0.0;	    jfnc=0.0;
}

/*----------------------------------------------------------------*/
void wrt_html(int flg) {

/*if (fh!=NULL) /**/
switch (flg){
case 0: {
    fprintf(fh,"<!DOCTYPE NETSCAPE-Bookmark-file-1>\n");
    fprintf(fh,"<!-- This is an automatically generated file.\n");
    fprintf(fh,"It will be read and overwritten.\n");
    fprintf(fh,"Do Not Edit! -->\n");
    fprintf(fh,"<TITLE>Nick Schmitz's Bookmarks</TITLE>\n");
    fprintf(fh,"<H1>Nick Schmitz's Bookmarks</H1>\n");
    fprintf(fh,"\n");
    fprintf(fh,"<DL><p>\n");
    fprintf(fh,"    <DT><H3 FOLDED ADD_DATE=\"872639532\">Lattice Semiconductor Inc.</H3>\n");
    fprintf(fh,"    <DL><p>\n");
    fprintf(fh,"\n");
    fprintf(fh,"<HR>\n");
    fprintf(fh,"<DT><A HREF=\"http://www.latticesemi.com\">Lattice</A>\n");
break;
}
case 1:{
    fprintf(fh,"<DT><A HREF=\"http://www.deja.com/=zdnet/[ST_rn=ps]/qs.xp?ST=PS\n");
    fprintf(fh,"&QRY=hershey&defaultOp=AND&DBS=1&OP=dnquery.xp&LNG=ALL&subjects=\n");
    fprintf(fh,"&groups=misc.invest.*&authors=\n");
    fprintf(fh,"&fromdate=aug+19+1998&todate=today\n");
    fprintf(fh,"&showsort=date&maxhits=100/\">Jack Hershey Posts</A>\n");
break;
}
case 2:{
    fprintf(fh,"<HR>\n");
    fprintf(fh,"<DT><A HREF=\"http://quote.yahoo.com/d/quotes.csv?s=\n");
break;}
case 3:{
    fprintf(fh,"lscc+\n");
    fprintf(fh,"&f=sl1d1t1c1ohgv&e=.csv\">W/L Data Download</A>\n");
break;}
case 4:{
    fprintf(fh,"<DT> <A HREF=\"http://quote.yahoo.com/q?s=\n");
break;}
case 5:{
    fprintf(fh,"lscc+\n");
    fprintf(fh,"&d=0b\">W/L Charts</A>\n");
break;}
case 6:{
    fprintf(fh,"<HR>\n");
    fprintf(fh,"<TT>\n");
    fprintf(fh,"<PRE>\n");
break;}
case 7:{
    fprintf(fh,"                 \\|/ \n");
    fprintf(fh,"                (@ @)\n");
    fprintf(fh,"     +----oOO----(_)-----------+\n");
    fprintf(fh,"     |       Jack Hershey      |\n");
    fprintf(fh,"     |           for           |\n");
    fprintf(fh,"     |        President        |\n");
    fprintf(fh,"     +-----------------oOO-----+\n");
    fprintf(fh,"               |__|__|  \n");
    fprintf(fh,"                || ||\n");
    fprintf(fh,"               ooO Ooo\n");
break;}
case 8:{
    fprintf(fh,"</PRE>\n");
    fprintf(fh,"</TT>\n");
break;}
case 9:{
    fprintf(fh,"<HR>\n");
    fprintf(fh,"</DL><p>\n");
break;}
case 10:{
    fprintf(fh,"<HR>\n");
    fprintf(fh,"<DT><A HREF=\"http://quote.yahoo.com/d/quotes.csv?s=\n");
break;}
case 11:{
    fprintf(fh,"lscc+\n");
    fprintf(fh,"&f=sl1d1t1c1ohgv&e=.csv\">D/L - Univ.txt</A>\n");
break;}
}
} /* wrt_html */

/*----------------------------------------------------------------*/
double msb2d (long ii) /* Convert number format /**/
{
    char foo[4];
    char *p;
    long expo,j,k;
    int  sign;
    double x,rslt;

    p=&ii;
    expo=p[3]+104; /* -$98 /**/
    if (expo>128) expo=expo-256;
    if (expo==104) expo=-152;
    k=1;
    sign=1;
    if (ii & 1<<23) sign=-1;

    j=ii | 1<<23; 		/* $0.80.00.00 /**/
    j= j & ((1<<24)-1); 	/* $0.FF.FF.FF /**/

/*----------------------------------------------------------------*/
    if (dbg>7) printf(" %d %d %d %d \n",p[0], p[1], p[2], p[3]);/**/
    if (dbg>7) printf(" %12ld %12ld    %d %d ",ii, j, sign, expo);/**/

    if ((expo<=32) && (expo>-32))
        {
        if (expo>=0) x=k<< expo;
                else x=k<<-expo;
        rslt=sign*j/x;
        }
      else
        {
/*        x=exp(expo*log(2.0));
        rslt=sign*j*x;/**/
        rslt=0.0;
        }
     if (dbg>7) printf("%12.3f %12.3f \n",x,rslt);/**/
     return(rslt);

} /* msb2d */

/*----------------------------------------------------------------*/
void opn_file(int argc, char *argv[])
{
     char  cbuf[25];
     int j,k,m,q;
/*----------------------------------------------------------------*/
/*     printf("%s \n",*argv);/**/
/*     printf("%s \n",*++argv);/**/
/*----------------------------------------------------------------*/
/*   for (k=1; k<60; k++) printf("*");   printf(" \n"); /**/
/*----------------------------------------------------------------*/
/*	File access stuff - handle errors & exit		  */
/*----------------------------------------------------------------*/
     *++argv;/**/    /* Skip Prog Name */
     ln=1;
     if ((argc==1) & (lop<0)) {
		  printf("Need file name \n");
		  ln=29999;
/*		  exit(1); /**/
		  }

         if ((lop<0) && (argc>1)) strcpy(a_str,*argv);
            else strcpy(a_str,y_str);

	if (dbg>0) printf("$%s$\n",a_str);
	q=0; csv=0;
	for (k=0; a_str[k]; k++) { if (a_str[k]=='.') q=k; }
	if (q!=0) if ((a_str[q+1]=='c') || (a_str[q+1]=='C')) csv=1;
	if (dbg>2) printf("%s %d\n",a_str, csv);

	if((fp = fopen(a_str, "rb")) == NULL) {/**/

		cbuf[0]=a_str[0];  cbuf[1]=0;

/*----------------------------------------------------------------*/
		strcpy(a_str,sLoc);/**/
/*		strcpy(a_str,"c:\\tc2000\\data\\");/**/
/*		strcpy(a_str,"e:\\tc2000cd\\");/**/
/*----------------------------------------------------------------*/
		strcat(a_str,cbuf);
		strcat(a_str,"\\");/**/

		if ((lop<0) && (argc>1)) strcat(a_str,*argv);
			else strcat(a_str,y_str);

		q=0; csv=0;
		for (k=0; a_str[k]; k++) { if (a_str[k]=='.') q=k; }
		if (q==0) strcat(a_str,".ndx");/**/
		if (dbg>2) printf("%s\n",a_str);

		if((fp = fopen(a_str, "rb")) == NULL) {
		       printf("Cannot open file \"%s\" - %s\n",*argv,a_str);
			ln=29999;
/*		       exit(1);/**/
		  }
	  } /* open fail/**/
/*----------------------------------------------------------------*/
	if(argc>2){  /* pick up date from command line /**/
        	*++argv;/**/    /* Skip stk sym */
		sscanf(*argv, "%f %[^\n]s", &date, &b_str); /**/
		if (dbg>2) printf("C %s %f  \n",*argv, date);/**/

     } else {date=0.0;}

/*  date=980501; /**/
/*----------------------------------------------------------------*/
   q=0;
   for (k=0; a_str[k]; k++) { if (a_str[k]=='\\') q=k; }
   if (q>0) q++;

   for (k=0; a_str[q]!='.' && a_str[q]; k++) c_str[k]=a_str[q++];
   c_str[k++]=0;/**/
}
/*----------------------------------------------------------------*/
void rd_tc2k(int argc, char *argv[])
{
     char  cbuf[25];
     int   jbuf[11];
     long  lbuf[6];
     float v[6];

/*     int j,k,m,q;/**/
    int j,k,q;
	 int r,s;
	 int tmp;

/*----------------------------------------------------------------*/
    opn_file(argc, argv);
/*----------------------------------------------------------------*/
	if (csv<1){
    fread(&cbuf,sizeof(cbuf)-1,1,fp);   /* read stock name */
    cbuf[24]=0;
    strcpy(b_str,cbuf);
    if (dbg>2) printf("\"%s\"\n",cbuf);/**/

    fread(&jbuf,sizeof(jbuf),1,fp); 	/* skip data flags */
    if (dbg>7) {for (q=0; q<=10; q++) printf("%8d ",jbuf[q]); printf("\n");}

    fread(&q,sizeof(q),1,fp);   /* Some off-by-one problem */
	}
    lnc=0; j=0;
/*----------------------------------------------------------------*/
    if (dbg>2) printf("\"date\",\"open\",\"high\",\"low\",\"close\",\"vol\"\n");

    do_init();
    for (ln=ln; ln<2510 && feof(fp)==0; ln++)  /* daily data */
       {
	if (csv<1){
	    	fread(&lbuf,sizeof(lbuf),1,fp);
        	for (q=0; q<=5; q++) v[q]=msb2d(lbuf[q]);

	} else {
/*		19980908,3.50,3.50,3.25,3.25,33400 /**/
		fgets(time,MAX_LINE_LENGTH,fp);

		for (q=0; time[q]; q++) if (time[q]==',') time[q]=' ';
		if (time[0]=='1') { time[0]=' '; time[1]=' '; }

		sscanf(time,"%f %f %f %f %f %f",
			&v[0], &v[5], &v[1], &v[2], &v[3], &v[4]); /**/
		v[4]=v[4]/100;
	}
	if (v[0]<900101) v[0]=v[0]+1000000;/**/

        tvol=v[4]*100;	/* Data for analysis /**/
        high=v[1];        lowp=v[2];
        opnp=v[5];        clse=v[3];

        strcpy(b_str,cbuf);
        tprc=(high+lowp)/2.0+0.001;

/* printf("%6.0f,%6.3f,  %6.3f,%6.3f,  %6.3f,%6.0f\n",
           		   v[0], v[5],   v[1], v[2],   v[3], v[4]*100); /**/
/*----------------------------------------------------------------*/
   if ((tvol>2999.0) && (v[0]>ldat) && (v[0]<zdat)){   lnc++; ldat=v[0];/**/

/* printf("1\n");                   /**/
/*   if ((tvol>2999.0) && ( (v[0]>date) || (v[0]>101) )){   lnc++; /**/
       date=v[0]; 	/* Format: date-YYMMDD */
	if (date>991231) date=v[0]-1000000;/**/

        if (dbg>2) printf("%6.0f,%6.3f,  %6.3f,%6.3f,  %6.3f,%6.0f\n",
           		   v[0], v[5],   v[1], v[2],   v[3], v[4]*100);
/*	printf("%6.0f,%6.3f,  %6.3f,%6.3f,  %6.3f,%6.0f *!\n",
		date , opnp,   high,lowp,   clse, tvol); /**/
/*	if (dbg>7) for (q=0; q<=5; q++) printf("%10ld",lbuf[q]);
        if (dbg>7) printf("%d \n",ln);/**/

/*----------------------------------------------------------------*/
/* stoc & rsi calc 5/1/99 */
	if (stck<0) {
		for (q=0; q<9; q++) hgcl[q]=high;
		for (q=0; q<9; q++) lwcl[q]=lowp;
		for (q=0; q<9; q++) rsiv[q]=clse-opnp+0.001;
		stck=1; rsio=1; styk=1; rsyo=1;
	   } else upd_rs();

        upd_ma();
        ck_trade();

/*----------------------------------------------------------------*/
       lstp=tprc; lstc=clse; lstv=tvol;
     j=0; } else j++; /* tvol>0 /**/
   } /* each day/**/
 fclose(fp);
 tprc=lstp;
 if (j>2) tprc=-tprc;
/* printf ("***%d %6.2f\n",j, tprc);/**/
/*----------------------------------------------------------------*/
/* Main output display /**/
/*----------------------------------------------------------------*/
  if (ln<2999) /* no file */
  	if(argc>2){
		printf("....\n");
		out_dsp();
	  } else {
		out_dsp();
		printf( "\n");
	  }
	else fprintf(fb,"%s+\n",c_str);/**/
/*----------------------------------------------------------------*/
} /* rd_tc2k */

/*----------------------------------------------------------------*/
void get_stk(int argc, char *argv[])
{
     int lnx, x,y,z;

      if ((fx = fopen(x_str, "r")) != NULL) {/**/
/*----------------------------------------------------------------*/
        for (lnx=1; (lnx<mxf) && fgets(x_str,MAX_LINE_LENGTH,fx); lnx++) {
		for (x=0; x_str[x]; x++) if (x_str[x]=='+') x_str[x]=' ';
		for (x=0; x_str[x]; x++) if (x_str[x]=='*') x_str[x]=' ';
		for (x=0; x_str[x]; x++) if (x_str[x]=='"') x_str[x]=' ';
		for (x=0; x_str[x]; x++) if (x_str[x]==',') x_str[x]=' ';

		sscanf(x_str,"%s%[^\n]", &y_str, &z_str);
		if (dbg>2) printf("*%s*\n",y_str); /**/
		rd_tc2k(argc, argv);

		tvol=0;
		sscanf(x_str,"%s%f%s%s %s%f%f%f%f",
            		&y_str, &clse, &z_str, &time, &z_str, &opnp,
 			&high, &lowp, &tvol);

/*----------------------------------------------------------------*/
/*		if (dbg>=0) {printf("*%s*%d*\n",x_str, lnx);}/**/
/* "ACTM",16.6875,"3/8/1999","12:04PM",-0.4375,17.125,17.375,16.5,18700 /**/
/*----------------------------------------------------------------*/
		sscanf(time,"%[^:]%[:]%2c",  &x_str, &z_str, &z_str);
		z_str[2]=0;
		sscanf(x_str,"%d",  &x);
		sscanf(z_str,"%d",  &y);
/*        	printf("$$*%s*%d,%d,%d,*%s*",x_str, z, x, y, z_str);/**/

		sscanf(time,"%[^:]%[:]%2c%c",  &x_str, &z_str, &z_str, &z_str);
/*        	printf("*%s*%d,%d,%d,*%s*\n",z_str, z,x,y, time);/**/

/*----------------------------------------------------------------*/
		if ((z_str[0]=='A') || (x==12)) {z=x*60+y;}
			else { z=(12+x)*60+y;}
/*		z=(10*z-3850)/57; /* rescale 0-100 6:30am-1:00pm */
		z=(10*z-5750)/39; /* rescale 0-100 9:30am-4:00pm */

		if (z<0.5) z=1.6*z; /* downplay early vol */
        	if (dbg>2) printf("*%s*%d,%d,%d,*%s*\n",z_str, z,x,y, time);/**/
		if (z>100) z=100;/**/
		if (z<=0) z=1;/**/

		tvol=(tvol*100)/z;
		tprc=(high+lowp)/2+0.001;
		date++;

/*----------------------------------------------------------------*/
	if (tvol>2999.0) { lop++; /* turn on output */
	if (dbg>1) {
       	printf("*%6s*%6.2f,%6.2f,  %6.2f,%6.2f, %8.0f, %d,%d,%d,*%s*%6.0f\n",
		y_str, opnp, high, lowp, clse, tvol, z,x,y, time, date);}/**/

/*----------------------------------------------------------------*/
		upd_rs();
		upd_ma();

		chx='^'; z=dbg; dbg=2;
		ck_trade();
		chx=';'; dbg=z;
		out_dsp();
		lop--; /* off */
	  }
/*----------------------------------------------------------------*/
	} /* each line */
	printf ("\n");
	fclose (fx);
	} /* open quotes */
} /* get_stk/**/

/*----------------------------------------------------------------*/
void do_html(int flg){ /* produces html */
/* Sections:
	Download List, Chart List, Action List,
	DB Bulk Dwnload, Buy/Sell */

int x,y,z,q,r;
typedef struct {
	char pB[199][90];
	int  pX[199];
   } OBJ;
OBJ *pO;
/*-------------------------------------------------*/
	fh = fopen("zzz.htm", "wa");
	wrt_html( 0);	wrt_html( 1);	wrt_html( 2);

/*-------------------------------------------------*/
	if((fb = fopen("zzz.zz2", "ra"))!=NULL) { /* Download list */
		for (x=0; (x<mxf) && fgets(x_str,MAX_LINE_LENGTH,fb); x++) {
			for (y=0; (x_str[y]!='+'); y++) y=y;
			x_str[y]=0;
			if (y!=0) fprintf(fh,"%s+\n",x_str);}
		fclose(fb);
	  }

	wrt_html( 3); wrt_html( 4);

/*-------------------------------------------------*/
	if((fb = fopen("zzz.zz2", "ra"))!=NULL) { /* Chart List */
		for (x=0; (x<mxf) && fgets(x_str,MAX_LINE_LENGTH,fb); x++) {
			for (y=0; (x_str[y]!='+'); y++) y=y;
			x_str[y]=0;
			if (x_str[y+1]=='*') fprintf(fh,"%s+\n",x_str);}
		fclose(fb);
	  }
	if((fb = fopen("zzz.zz2", "ra"))!=NULL) { /* Chart List */
		for (x=0; (x<mxf) && fgets(x_str,MAX_LINE_LENGTH,fb); x++) {
			for (y=0; (x_str[y]!='+'); y++) y=y;
			x_str[y]=0;
			if ((x_str[y+1]!='*') && (y!=0))
				fprintf(fh,"%s+\n",x_str);}
		fclose(fb);
	  }
	wrt_html( 5);

/*-------------------------------------------------*/
 	if((fa = fopen("zzz.zz1", "ra"))!=NULL) { /* Action List */

		pO = ((OBJ *) malloc(sizeof(OBJ)));
	
	        for (x=0; (x<99) && fgets(x_str,MAX_LINE_LENGTH,fa); x=x)
        		if (x_str[0]!=';') strcpy(pO->pB[x++],x_str);
		fclose(fa);

/*	        for (y=0; y<x; y++) fprintf(fh,"%s",pO->pB[y]);
		fprintf(fh,"\n %3d - Actions, %3d - Watches\n\n",x-fa_ctr+1,fa_ctr);/**/

/*-------------------------------------------------*/
		for (y=0; y<x; y++) pO->pX[y]=y;

		for (y=0; y<x; y++) for (z=y+1; z<x; z++) { /* bubble sort */
		   for (q=3; ((q<15) && (pO->pB[pO->pX[y]][q]
			==pO->pB[pO->pX[z]][q])); q++) {q=q;} /* find unequal*/

		   if(pO->pB[pO->pX[y]][q]<pO->pB[pO->pX[z]][q]) /* swap? */
			{r=pO->pX[y]; pO->pX[y]=pO->pX[z]; pO->pX[z]=r;}}

/*-------------------------------------------------*/
	wrt_html( 4);
	        for (y=0; y<x; y++) {
	        	for (z=17; z<23; z++)
		  	 if (pO->pB[pO->pX[y]][z]!=' ')
			  	 fprintf(fh,"%c",pO->pB[pO->pX[y]][z]);
		   fprintf(fh,"+\n");
		  }


	wrt_html( 5);

	wrt_html( 6);
	if (flg==0) fprintf(fh,"Todays Actions: (Nite)\n\n");
		else fprintf(fh,"Todays Actions: (Day)\n\n");

/*-------------------------------------------------*/
		fprintf(fh," Action, rMx/Mn,  Stock,   Date, Stp-Lmt,");
		fprintf(fh,"  #-Shr,  Price,   Rmin,  Rmax,Days\n");

	        for (y=0; y<x; y++) {
		   if ((y>0) && (pO->pB[pO->pX[y]][6]!=pO->pB[pO->pX[y-1]][6]))
	        	fprintf(fh,"\n");
		   fprintf(fh,"%s",pO->pB[pO->pX[y]]);
		  }

		fprintf(fh,"\n %3d - Actions, %3d - Watches\n\n",x-fa_ctr,fa_ctr);
		free(pO);
	}
	if (fa_ctr==0) wrt_html( 7);/**/
	if (dbg>2) wrt_html( 7);/**/

/*-------------------------------------------------*/
	wrt_html( 8);
	if((fb = fopen("zzz.zz2", "ra"))!=NULL) { /* Download list */
 		fprintf(fh,"<HR>\n<TT>\n<PRE>\nCSV - Downloads:\n");
		fprintf(fh,"</PRE>\n</TT>\n");
		for (x=0; (x<mxf) && fgets(x_str,MAX_LINE_LENGTH,fb); x++) {
		   for (y=0; (x_str[y]!='+'); y++) y=y;
		   if (y>0) {
			x_str[y]=0;
			   fprintf(fh,"<DT> <A HREF=\"http://chart.yahoo.com/table.csv");
			   fprintf(fh,"?s=%s\n",x_str);
			   fprintf(fh,"&a=09&b=07&c=98&d=12&e=31&f=99");
			   fprintf(fh,"&g=d&q=q&y=0&x=.csv\">D/L - %s</A>\n",x_str);
		}}
		fclose(fb);
	  }
/*-------------------------------------------------*/
	wrt_html( 10);

/*-------------------------------------------------*/
	if((fb = fopen("univ.txt", "ra"))!=NULL) { /* Download list */
		for (x=0; (x<mxf) && fgets(x_str,MAX_LINE_LENGTH,fb); x++) {
			for (y=0; ((x_str[y]!='.') && (x_str[y])); y++) y=y;
			if (x_str[y]=='.') x_str[y]=0; else x_str[y-1]=0;
			q=0;
			for (y=0; x_str[y]; y++) if (x_str[y]=='\\') q=y;
			if (q==0) fprintf(fh,"%s+\n",x_str);}
		fclose(fb);
	  }

	wrt_html(11);

/*-------------------------------------------------*/
	wrt_html(6);
 	if((fa = fopen("zzz.zz1", "ra"))!=NULL) { /* Buy/Sell for N-STK */
	        for (x=0; (x<99) && fgets(x_str,MAX_LINE_LENGTH,fa); x++)
        		if (x_str[0]==';') fprintf(fh,"%s",x_str);
		fclose(fa);}
	wrt_html(6);

/*-------------------------------------------------*/
	wrt_html( 9);
	fclose(fh);
}
/*----------------------------------------------------------------*/
void do_univ(int flg){ /* runs get_stk & collects output for html */
int q;
	lop=2; if (flg!=0) lop=1;

	tday=0.0;	ttrd=0.0;	tbal=0.0;
	tlrg=0.0;	tsml=9.9E9;	tstk=0;

	for (q=0; q<7; q++) { phst[q]=dhst[q]=0; }

	pbin[0]=-500;	pbin[1]=50;	pbin[2]=500;
	pbin[3]=1500;	pbin[4]=2500;	pbin[5]=5000;
	pbin[6]=-9999;
	dbin[0]=2;	dbin[1]=4;	dbin[2]=6;
	dbin[3]=8;	dbin[4]=11;	dbin[5]=15;
	dbin[6]=-1;

/*-------------------------------------------------*/
	if (flg==0)  strcat(x_str,"univ.txt");
		else strcat(x_str,"quotes.csv");
	printf("* Processing files from: - %s\n",x_str);/**/
	printf ("\n$!!$56789a123456789b123456789c123456789d123456789e123456789f\n");

/*-------------------------------------------------*/
	fa = fopen("zzz.zz1", "wa");
	fb = fopen("zzz.zz2", "wa");
	get_stk(1, NULL);		/* Process stock list */
	fclose(fb);
	fclose(fa);
	do_html(flg);

/*	tstk=tstk/2; /* counted twice */

	if ((flg==0) && (ttrd>0.0) && (tday>0.0)) {
	printf ("\n$!!$ --------------------------------\n");
    printf ("\n$!!$ jh, %6.0f, %6.0f, %6.0f,%8.0f,%5.0f,",
			     tlrg, ttrd,  tday,  tbal, tbal/ttrd);
    printf ("%5.0f,%4.1f,%4.0f,%5.0f,%5.1f\n",
  	tbal/tday, tday/ttrd, tstk, tsml,(phst[0]+phst[1])/ttrd*100);
	printf ("\n$!!$56789a123456789b123456789c123456789d123456789e123456789f\n");
	if (dbg>0) dsp_hst();
	wrt_key();
	}
} /* do_univ */

/*----------------------------------------------------------------*/
main(int argc, char *argv[]) /* stkscn file_name date dbg1 dbg2 /**/
{
int x,y;
/*      printf("*%d*%s*\n",argc, *argv); /**/

	dbg=0; y_str[0]=0; lop=-1;
	fh=NULL; fa=NULL; fb=NULL;
	fa_ctr=0;

	if(argc>4) { dbg=3; }
		else if(argc>3) { dbg=2; }
		else if(argc>2) { dbg=1; }
		else { dbg=0; }
/*	dbg=1;/**/

/*-------------------------------------------------*/
    zdat=1991231;
	if((fb = fopen("zzz.dat", "ra"))!=NULL) {
		fgets(sLoc,MAX_LINE_LENGTH,fb);
		sscanf(sLoc, "%s %s %s %s %s",
			&b_str, &b_str, &b_str, &b_str, sLoc); /**/
		for (x=0; sLoc[x]; x++) if (sLoc[x]=='-') sLoc[x]=' ';
		sscanf(sLoc,"%f %f %f", &opnp, &high, &lowp); /**/
		printf("***%f %f %f %f\n", zdat, opnp, high, lowp);
		zdat=high;
		printf("***%s %7.0f***\n",sLoc, zdat);
		zdat=zdat+(100.0*opnp);
		printf("***%s %9.2f***\n",sLoc, zdat);
		if (lowp>=2000) zdat=zdat+(1000.0*(lowp-1000));
			else zdat=zdat+10000.0*(lowp-1900);
		printf("***%s %9.2f***\n",sLoc, zdat);
		fclose(fb);
	}
/*-------------------------------------------------*/
	y=0;
	strcpy(x_str,*argv);
/*	printf("%s\n",x_str); /**/
	for (x=0; x_str[x]; x++) if (x_str[x]=='\\') y=x;
	y++; mxf=19;
	if (x_str[y+2]=='S') mxf=9999;
/*	if (argc>2) {printf("mxf -!  %d %c\n", mxf, x_str[y+2]);} /**/
	x_str[y]=0;

	strcpy(sLoc,x_str);
	strcat(sLoc,"univ.txt");
	if((fb = fopen(sLoc, "ra"))!=NULL) {
		fgets(sLoc,MAX_LINE_LENGTH,fb);
		y=0;
		for (x=0; sLoc[x]; x++) if (sLoc[x]=='\\') y=x;
		if (y==0) strcpy(sLoc,"c:\\tc2000\\data\\");
			else { y++; sLoc[y]=0; }
		printf("* Data location: - %s\n",sLoc);
		fclose(fb);
	} else strcpy(sLoc,"c:\\tc2000\\data\\");

/*-------------------------------------------------*/
	if (argc<2 ) do_univ(1);
	  else {
		strcpy(a_str,*++argv);
		for (x=0; a_str[x]; x++) /* case fold to lower */
			if (a_str[x]<='Z') a_str[x]=a_str[x]+32;
		if (argc>2) {flx=0; ++argv; if (*argv[0]=='+') flx=1; --argv;}
/*		if (argc>2) {printf("flx -!  %d %s\n", flx, *++argv); --argv;}/**/
		--argv;
		a_str[4]=0; /* chop length */
		if      (strcmp(a_str,"univ")==0) do_univ(0);
		else if (strcmp(a_str,"quot")==0) do_univ(1);
		else if (strcmp(a_str,"upda")==0) do_univ(2);
			else { rd_tc2k(argc, argv);
				wrt_key();}
	   }
}
/*----------------------------------------------------------------*/
